### ISSUE TITLE
Enable hardware accelerated video decoding/rendering

### ISSUE THREAD

**Issue by steveatinfincia** [infincia/QOpenHD#1]
The QtGStreamer video code is going to be replaced with qmlglsink, which is a modern and officially supported part of GStreamer.

This *dramatically* simplifies the code and puts responsibility for constructing the GStreamer pipeline inside the app itself. This allows us to do things like easily swap in other video sources, for example the videotestsrc component of GStreamer, which we're going to use to show a "video offline" screen whenever the real camera stream stops for whatever reason.

The GStreamer androidmedia plugin is not currently loading due to some additional build requirements but that will be resolved soon.

**Comment by steveatinfincia** [comment]
I've discovered the reason for the `androidmedia` plugin issues (and therefore the hardware decode acceleration issues on Android).

The `androidmedia` plugin is a complex bit of "glue code" that has to call out to Java via JNI in order to discover the available codecs on a particular Android device when the app first launches. In order to do that there is some build integration necessary, and Qt Creator/qmake ignores those steps at the moment.

I will have to take a look at what they're doing and add the appropriate build steps, but once that is done everything should work perfectly.

This is the only thing holding up integration of the more modern `qmlglsink` video rendering system, it works very well everywhere else.

Reference: https://lists.freedesktop.org/archives/gstreamer-android/2016-September/001138.html

**Comment by pilotnbr1** [comment]
Very nice!

**Comment by steveatinfincia** [comment]
Hardware decode on Android is working well now, but the gstreamer `decodebin` element that automates the process of discovering available codecs currently has some quirks that prevent it from configuring zero-copy/direct rendering so it is currently doing a CPU->GPU copy for the frame data, which is inefficient.

Using the `amcviddec-*` elements directly, or possibly `playbin`, should allow zero-copy to work properly. This requires including a few Java classes from the GStreamer development package in builds which is not a problem.

**Comment by steveatinfincia** [comment]
Fixed in 464626210e92b5f2a4376df88f9316015646966d

**Comment by pilotnbr1** [comment]
Must be nice to finally close this!! nice job
