### ISSUE TITLE
Add tooltip buttons to setting rows

### ISSUE THREAD

**Issue by steveatinfincia** [infincia/QOpenHD#31]
It would be helpful to be able to tap a button on the settings rows and see more information about individual settings.

The easy way to do that is to add a Button instance to the delegates with a Tooltip instance inside it

**Comment by pilotnbr1** [comment]
This would be a great addition! I would be happy to go at this one once you put one example in place I can add the others and the text

**Comment by htcohio** [comment]
Steve,

That would be a great option!

Are you just thinking about a little information icon where there could be links to the wiki? 

If you could create the template, I can fill in a lot of the blanks

**Comment by steveatinfincia** [comment]
Implemented in 9cbcb94
